---
.travis.yml:
  use_containers: true
  script:
    - bundle exec rake validate
    - bundle exec rake lint
    - bundle exec rake spec SPEC_OPTS='--format documentation'
  forge_login: "camptocamp"
  includes:
    - rvm: "2.1"
      env: PUPPET_GEM_VERSION="~> 4.0"
    - rvm: "2.4"
      env: PUPPET_GEM_VERSION="~> 5.0"
    - rvm: "2.5"
      env: PUPPET_GEM_VERSION="~> 6.0"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rake
      - gem: rspec
      - gem: rspec-puppet
      - gem: puppetlabs_spec_helper
      - gem: metadata-json-lint
      - gem: puppet-lint
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-empty_string-check
      - gem: puppet-lint-spaceship_operator_without_tag-check
      - gem: puppet-lint-undef_in_function-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-file_ensure-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-file_source_rights-check
      - gem: puppet-lint-alias-check
      - gem: rspec-puppet-facts
      - gem: ruby-augeas
      - gem: puppet-blacksmith
        condition: 'RUBY_VERSION !~ /^1\./'
      - gem: json_pure
        version: '< 2.0.2'
    ':system_tests':
      - gem: puppet-module-posix-system-r#{minor_version}
Rakefile:
  default_disabled_lint_checks:
    - 'relative'
    - 'disable_80chars'
